#!/usr/bin/env bash
# Stamp a systemd unit for one of the demo UIs, with every path taken from THIS
# checkout rather than typed in.
#
# The templates beside this script carry the field-ops VM's own paths in five
# places each. Editing them by hand is how you get `203/EXEC`, which names no
# path at all and is indistinguishable from a missing interpreter, a missing
# app file and a WorkingDirectory that does not exist. This derives all five
# from its own location, checks each one exists, and prints the unit.
#
#   ./deploy/make_unit.sh pipeline                    # to stdout, read it
#   ./deploy/make_unit.sh pipeline | sudo tee /etc/systemd/system/fieldops-demo-pipeline.service
#   ./deploy/make_unit.sh modes --port 7874           # a second operator's copy
#
# It writes nothing itself. Redirect it where you want it, so the thing that
# needs root is a tee you can read first.
set -euo pipefail

usage() {
    cat >&2 <<USAGE
usage: $0 {pipeline|modes} [--venv PATH] [--user NAME] [--group NAME]
                           [--port N] [--host ADDR] [--env-file PATH]

  pipeline   frontend/demo_dash_pipeline.py, default port 7873
  modes      frontend/demo_dash_modes.py,    default port 7872

  --venv     the virtualenv to run under (default: autodetected in the
             checkout, preferring one that can import _ctypes)
  --user     service user  (default: whoever runs this)
  --port     override the app's port, for a second instance
  --host     bind address  (default 0.0.0.0; use 127.0.0.1 behind a proxy)
USAGE
    exit 2
}

[ $# -ge 1 ] || usage
APP="$1"; shift

case "$APP" in
    pipeline) SCRIPT=demo_dash_pipeline.py; PORT=7873
              DESC="domain, question, one photograph, three modes"; DOC=PLUGINS.md ;;
    modes)    SCRIPT=demo_dash_modes.py;    PORT=7872
              DESC="three pipeline modes over a folder";            DOC=MODES.md ;;
    *)        usage ;;
esac

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENV=""; RUN_USER="$(id -un)"; RUN_GROUP="$(id -gn)"
HOST=0.0.0.0; ENV_FILE=/etc/fieldops-demo.env

while [ $# -gt 0 ]; do
    case "$1" in
        --venv)     VENV="$2";      shift 2 ;;
        --user)     RUN_USER="$2";  shift 2 ;;
        --group)    RUN_GROUP="$2"; shift 2 ;;
        --port)     PORT="$2";      shift 2 ;;
        --host)     HOST="$2";      shift 2 ;;
        --env-file) ENV_FILE="$2";  shift 2 ;;
        *) echo "unknown option: $1" >&2; usage ;;
    esac
done

# ── Find an interpreter ──────────────────────────────────────────────────────
# SETUP.md records a venv on this VM built against a python without _ctypes,
# which imports fine and then fails deep inside a dependency. Prefer one that
# passes that check, and say so when none does rather than stamping it silently.
if [ -n "$VENV" ]; then
    CANDIDATES="$VENV/bin/python"
else
    CANDIDATES="$(ls -d "$ROOT"/*/bin/python "$ROOT"/.*/bin/python 2>/dev/null || true)"
fi
PYTHON=""
for candidate in $CANDIDATES; do
    [ -x "$candidate" ] || continue
    if "$candidate" -c 'import _ctypes' 2>/dev/null; then PYTHON="$candidate"; break; fi
    [ -n "$PYTHON" ] || PYTHON="$candidate"      # remember the first, keep looking
done
if [ -z "$PYTHON" ]; then
    echo "no virtualenv found under $ROOT - pass --venv PATH" >&2
    exit 1
fi
if ! "$PYTHON" -c 'import _ctypes' 2>/dev/null; then
    echo "WARNING: $PYTHON cannot import _ctypes - see SETUP.md. Stamping it" >&2
    echo "         anyway, but the app will fail inside a dependency, not at" >&2
    echo "         startup, which reads as a broken app rather than a bad venv." >&2
fi

APP_PATH="$ROOT/frontend/$SCRIPT"
[ -f "$APP_PATH" ] || { echo "not found: $APP_PATH" >&2; exit 1; }

cat <<UNIT
# Generated by deploy/make_unit.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ) from
#   $ROOT
# Re-run that script after moving the checkout; do not hand-edit the paths.

[Unit]
Description=Field Ops demo - $DESC (Dash, port $PORT)
Documentation=file://$ROOT/$DOC
# network-online, not just network: the app contacts the LLM proxy while
# building its status line, and "network" alone is satisfied before an address
# is actually configured.
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$RUN_USER
Group=$RUN_GROUP
WorkingDirectory=$ROOT

# The API key lives here, not in this file: a unit file is world-readable by
# design, and \`systemctl cat\` prints it to anyone who asks. Keep the env file
# at chmod 600. The leading '-' means the service still starts if it is absent
# - useful when the proxy runs with auth disabled.
EnvironmentFile=-$ENV_FILE

# Unbuffered, or journalctl shows nothing until Python flushes - which during
# a slow pipeline run can be minutes.
Environment=PYTHONUNBUFFERED=1
Environment=DASH_HOST=$HOST
Environment=DASH_PORT=$PORT

ExecStart=$PYTHON $APP_PATH

Restart=always
RestartSec=5
# A run holds the worker for seconds per photograph; give it room to finish
# rather than killing it mid-batch on stop.
TimeoutStopSec=30
KillSignal=SIGINT

StandardOutput=journal
StandardError=journal
SyslogIdentifier=fieldops-demo-$APP

[Install]
WantedBy=multi-user.target
UNIT
